// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgTkqkyF6CK9ShGrSQyEkPdBe5MfaNDo',
    appId: '1:1000318033211:web:43ee5a940afc6e3ce32b1e',
    messagingSenderId: '1000318033211',
    projectId: 'historical-bot-login',
    authDomain: 'historical-bot-login.firebaseapp.com',
    storageBucket: 'historical-bot-login.appspot.com',
    measurementId: 'G-7X99LZSVKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsGz680QcrZGoQviizfNPoiw5UFXjP4_Y',
    appId: '1:1000318033211:android:6a582b03ead0b845e32b1e',
    messagingSenderId: '1000318033211',
    projectId: 'historical-bot-login',
    storageBucket: 'historical-bot-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu7lwN0D8GqT0tMj7Gm8GdNPjKxNAQ2gk',
    appId: '1:1000318033211:ios:68a7c2dd19748762e32b1e',
    messagingSenderId: '1000318033211',
    projectId: 'historical-bot-login',
    storageBucket: 'historical-bot-login.appspot.com',
    iosBundleId: 'com.example.historicalBotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu7lwN0D8GqT0tMj7Gm8GdNPjKxNAQ2gk',
    appId: '1:1000318033211:ios:09f4623e38fa04e1e32b1e',
    messagingSenderId: '1000318033211',
    projectId: 'historical-bot-login',
    storageBucket: 'historical-bot-login.appspot.com',
    iosBundleId: 'com.example.historicalBotApp.RunnerTests',
  );
}
